/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class boofcv_drivers_stereo_CameraBumblebee2_Interpolation */

#ifndef _Included_boofcv_drivers_stereo_CameraBumblebee2_Interpolation
#define _Included_boofcv_drivers_stereo_CameraBumblebee2_Interpolation
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
