/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class boofcv_drivers_stereo_CameraBumblebee2 */

#ifndef _Included_boofcv_drivers_stereo_CameraBumblebee2
#define _Included_boofcv_drivers_stereo_CameraBumblebee2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     boofcv_drivers_stereo_CameraBumblebee2
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_boofcv_drivers_stereo_CameraBumblebee2_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     boofcv_drivers_stereo_CameraBumblebee2
 * Method:    grabRGB
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_boofcv_drivers_stereo_CameraBumblebee2_grabRGB
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     boofcv_drivers_stereo_CameraBumblebee2
 * Method:    _init
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_boofcv_drivers_stereo_CameraBumblebee2__1init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     boofcv_drivers_stereo_CameraBumblebee2
 * Method:    _getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_boofcv_drivers_stereo_CameraBumblebee2__1getWidth
  (JNIEnv *, jobject);

/*
 * Class:     boofcv_drivers_stereo_CameraBumblebee2
 * Method:    _getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_boofcv_drivers_stereo_CameraBumblebee2__1getHeight
  (JNIEnv *, jobject);

/*
 * Class:     boofcv_drivers_stereo_CameraBumblebee2
 * Method:    getTimeStamp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_boofcv_drivers_stereo_CameraBumblebee2_getTimeStamp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
